version: '2'

services:
  wordpress:
    image: wordpress:php7.3
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DEBUG: 1
    volumes:
      - ..:/var/www/html/wp-content/plugins/geo-mashup
      - ../../geo-mashup-custom:/var/www/html/wp-content/plugins/geo-mashup-custom
      - uploads:/var/www/html/wp-content/uploads
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql
  install:
    image: juliquiron/wordpress-phpunit-test-runner-gitlab-ci
    volumes:
      - ..:/app
    working_dir: /app
    command: yarn install:dev

volumes:
  uploads:
  mysql:
