name: PHP Composer

on:
  push:
    branches: [ "develop", "feature/*" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root

    steps:
    - uses: actions/checkout@v3
    
    - name: Install WordPress testing tools
      run: bash tools/install-wp-tests.sh wordpress_test root root mysql latest

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: composer run-script test
